name: New Feature
description: Description of the newly added feature
labels: [feature]

body:
  - type: input
    id: feature-title
    attributes:
      label: Feature title
      description: "A short, descriptive title for the feature"
      placeholder: "e.g., Add custom shader support"
    validations:
      required: true

  - type: checkboxes
    id: feature-advancement
    attributes:
      label: Implementation status
      description: "Check what has already been done for this feature."
      options:
        - label: Feature is just an idea / not implemented yet
        - label: Prototype exists
        - label: Implementation complete
        - label: Related documentation updated
        - label: Tests written

  - type: textarea
    id: feature-description
    attributes:
      label: what does it add
      description: "What does this feature add or improve ?"
    validations:
      required: true

  - type: textarea
    id: feature-description-extra
    attributes:
      label: Additional context
      description: Add any other context or screenshots, links to designs, related issues, etc.
      placeholder: "Mockups, benchmarks, related issues, screenshots, references..."
    validations:
      required: false
