name: "Create Release"
on:
  workflow_dispatch:
  push:
    branches:
      - "*-release"

permissions:
  contents: write

env:
  PROJECT_FOLDER: test
  RELEASE_NAME: Release

jobs:
  get_date:
    runs-on: ubuntu-latest
    outputs:
      date_abr: ${{ steps.getdate.outputs.date_abr }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Date
        id: getdate
        run: |
          date_abr=$(date +"%g%m%d-%H%M")
          echo "date_abr=${date_abr}" >> $GITHUB_OUTPUT

  create_release:
    runs-on: ubuntu-latest
    needs: get_date
    steps:
      - name: create-release
        env:
          GH_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
